Repository saseungmin/summary_of_technical_books, pull requests merged in 2022-10, with the labels that each got.

#262 inspired part 1 오타 수정
  docs/etc/inspired/part-1.md
Labels: hacktoberfest-accepted, size/XS

#264 오타 교정
  docs/agile/nature-of-software-development/chapter-3.md
Labels: hacktoberfest-accepted, size/XS

#265 do-it-typescript/chapter-1 오타 수정
  docs/typescript/do-it-typescript/chapter-1.md
Labels: hacktoberfest-accepted, size/S

#266 clean-code/chapter-1 오타 수정
  docs/clean/clean-code/chapter-1.md
Labels: hacktoberfest-accepted, size/S

#268 Update chapter-1.md
  docs/etc/pragmatic-programmer/chapter-1.md
Labels: hacktoberfest-accepted, size/XS

#269 Update part-2.md
  docs/etc/inspired/part-2.md
Labels: hacktoberfest-accepted, size/XS

#270 Update chapter-1.md
  docs/object-oriented/facts-and-misunderstandings/chapter-1.md
Labels: hacktoberfest-accepted, size/XS

#271 growing-up-together/chapter-1.md 오타 수정
  docs/agile/growing-up-together/chapter-1.md
Labels: hacktoberfest-accepted, size/S

#272 실용주의 프로그래머|Chapter2 오타수정
  summarize_books_in_markdown/실용주의 프로그래머/Chapter 2/README.md
Labels: hacktoberfest-accepted, size/S

#275 클린 코드 #11 오탈자 수정
  docs/clean/clean-code/chapter-11.md
Labels: hacktoberfest-accepted, size/S

#276 clean-code/chapter-10 오타 수정
  docs/clean/clean-code/chapter-10.md
Labels: size/S

#273 오타 수정 및 내용 보충
  docs/agile/nature-of-software-development/chapter-19.md
  docs/clean/clean-code/chapter-10.md
Labels: hacktoberfest-accepted, size/S

#274 클린코드 #4 오타 수정
  docs/clean/clean-code/chapter-4.md
Labels: size/XS

#277 클린 코드 #6 오탈자 수정
  docs/clean/clean-code/chapter-6.md
Labels: hacktoberfest-accepted, size/S

#278 오브젝트 오타 수정
  docs/object-oriented/object/chapter-15.md
Labels: hacktoberfest-accepted, size/S

#280 Update chapter-13.md
  docs/object-oriented/object/chapter-13.md
Labels: size/XS

#279 Update chapter-14.md
  docs/object-oriented/object/chapter-14.md
Labels: hacktoberfest-accepted, size/S

#281 Update chapter-12.md
  docs/object-oriented/object/chapter-12.md
Labels: hacktoberfest-accepted, size/S

#282 docs: tdd, unit test, effective-typescript 책을 추가하라
  README.md
  docs/etc/_category_.json
  docs/intro.md
  docs/object-oriented/table-of-contents.md
  docs/test/_category_.json
  docs/test/growing-object-oriented-software-guided-by-tests/_category_.json
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-1.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-10.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-11.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-12.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-13.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-14.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-15.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-16.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-17.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-18.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-19.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-2.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-20.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-21.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-22.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-23.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-24.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-3.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-4.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-5.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-6.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-7.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-8.md
  docs/test/growing-object-oriented-software-guided-by-tests/chapter-9.md
  docs/test/growing-object-oriented-software-guided-by-tests/table-of-contents.md
  docs/test/table-of-contents.md
  docs/test/test-driven-development/_category_.json
  docs/test/test-driven-development/table-of-contents.md
  docs/test/unt-test/_category_.json
  docs/test/unt-test/table-of-contents.md
  docs/typescript/effective-typescript/_category_.json
  docs/typescript/effective-typescript/table-of-contents.md
  docs/typescript/table-of-contents.md
  docusaurus.config.js
  images/effective-typescript.jpeg
  images/tdd.jpeg
  images/unit-test.jpeg
  src/data/books.js
  static/img/books/effective-typescript.jpeg
  static/img/books/tdd.jpeg
  static/img/books/unit-test.jpeg
Labels: hacktoberfest-accepted, size/L

#283 객체지향의 사실과 오해: 문장 오타 수정
  summarize_books_in_markdown/객체지향의 사실과 오해/Chapter 1/README.md
  summarize_books_in_markdown/객체지향의 사실과 오해/Chapter 2/README.md
  summarize_books_in_markdown/객체지향의 사실과 오해/Chapter 5/README.md
Labels: hacktoberfest-accepted, size/L

#287 docs: 이펙티브 타입스크립트 chpater 1을 추가하라
  docs/typescript/effective-typescript/chapter-1.md
  docs/typescript/effective-typescript/table-of-contents.md
Labels: size/L

#285 실용주의 프로그래머 #3 오탈자 수정
  summarize_books_in_markdown/실용주의 프로그래머/Chapter 3/README.md
Labels: hacktoberfest-accepted, size/S

#286 객체지향의 사실과 오해 #3 오탈자 수정
  summarize_books_in_markdown/객체지향의 사실과 오해/Chapter 3/README.md
Labels: hacktoberfest-accepted, size/XS

#288 실용주의 프로그래머 #9 오탈자 수정
  summarize_books_in_markdown/실용주의 프로그래머/Chapter 9/README.md
Labels: hacktoberfest-accepted, size/S

#289 쉽게 배우는 알고리즘 #9 오탈자 수정
  summarize_books_in_markdown/쉽게 배우는 알고리즘/Chapter 9/README.md
Labels: hacktoberfest-accepted, size/XS

#290 docs: effective typescript chapter 1 내용을 추가하라
  docs/typescript/effective-typescript/chapter-1.md
  docs/typescript/effective-typescript/table-of-contents.md
Labels: hacktoberfest-accepted, size/L
