Repository saseungmin/summary_of_technical_books, pull requests merged in 2023-10, with the labels that each got.

#403 오탈자 수정
  docs/agile/nature-of-software-development/chapter-10.md
  docs/agile/nature-of-software-development/chapter-11.md
  docs/agile/nature-of-software-development/chapter-13.md
  docs/agile/nature-of-software-development/chapter-14.md
  docs/agile/nature-of-software-development/chapter-15.md
  docs/agile/nature-of-software-development/chapter-17.md
Labels: hacktoberfest-accepted, size/S

#405 오탈자 수정
  docs/functional/functional-javascript/table-of-contents.md
  docs/intro.md
  docs/typescript/effective-typescript/chapter-1.md
Labels: hacktoberfest-accepted, size/M

#406 오탈자 수정 - 이펙티브 타입스크립트 챕터 2~4
  docs/typescript/effective-typescript/chapter-2.md
  docs/typescript/effective-typescript/chapter-3.md
  docs/typescript/effective-typescript/chapter-4.md
Labels: hacktoberfest-accepted, size/M

#408 Patch clean code
  docs/clean/clean-code/chapter-1.md
  docs/clean/clean-code/chapter-12.md
  docs/clean/clean-code/chapter-13.md
  docs/clean/clean-code/chapter-2.md
  docs/clean/clean-code/chapter-3.md
  docs/clean/clean-code/chapter-4.md
  docs/clean/clean-code/chapter-5.md
  docs/clean/clean-code/chapter-6.md
  docs/clean/clean-code/chapter-7.md
  docs/clean/clean-code/chapter-9.md
Labels: hacktoberfest-accepted, size/M

#409 오탈자 수정 effective-typescript 5-8, modern-javascript table-of-contents
  docs/javascript/modern-javascript/table-of-contents.md
  docs/typescript/effective-typescript/chapter-5.md
  docs/typescript/effective-typescript/chapter-6.md
  docs/typescript/effective-typescript/chapter-7.md
  docs/typescript/effective-typescript/chapter-8.md
Labels: hacktoberfest-accepted, size/M

#410 fix: algolia appId값이 존재하지 않아서 ci가 실패하는 이슈 수정
  docusaurus.config.js
Labels: size/XS

#411 쉽게 배우는 알고리즘 수정 PR
  summarize_books_in_markdown/쉽게 배우는 알고리즘/Chapter 9/README.md
Labels: hacktoberfest-accepted, size/M

#419 youdontknowjs_오탈자수정, 문법 수정, 띄어쓰기 수정
  docs/javascript/you-dont-know-js/chapter-1.md
  docs/javascript/you-dont-know-js/chapter-2.md
  docs/javascript/you-dont-know-js/chapter-3.md
  docs/javascript/you-dont-know-js/chapter-4.md
  docs/javascript/you-dont-know-js/chapter-5.md
Labels: hacktoberfest-accepted, size/M

#420 growinguptogether/오타.띄어쓰기 수정
  docs/agile/growing-up-together/chapter-1.md
  docs/agile/growing-up-together/chapter-2.md
  docs/agile/growing-up-together/chapter-3.md
Labels: hacktoberfest-accepted, size/S

#421 progit-오탈자 수정
  docs/etc/pro-git-2/chapter-2.md
  docs/etc/pro-git-2/chapter-3.md
Labels: hacktoberfest-accepted, size/XS

#422 쉽게 배우는 알고리즘 수정 PR -2nd
  summarize_books_in_markdown/쉽게 배우는 알고리즘/Chapter 10/README.md
  summarize_books_in_markdown/쉽게 배우는 알고리즘/Chapter 6/README.md
Labels: hacktoberfest-accepted, size/S

#426 modern-javascript 챕터 1~10 오탈자 수정
  docs/javascript/modern-javascript/chapter-1.md
  docs/javascript/modern-javascript/chapter-10.md
  docs/javascript/modern-javascript/chapter-2.md
  docs/javascript/modern-javascript/chapter-3.md
  docs/javascript/modern-javascript/chapter-4.md
  docs/javascript/modern-javascript/chapter-5.md
  docs/javascript/modern-javascript/chapter-6.md
  docs/javascript/modern-javascript/chapter-7.md
  docs/javascript/modern-javascript/chapter-8.md
  docs/javascript/modern-javascript/chapter-9.md
Labels: hacktoberfest-accepted, size/L

#428 clean-code Chapter 4,5,6 오탈자 수정
  summarize_books_in_markdown/clean-code/Chapter 4/README.md
  summarize_books_in_markdown/clean-code/Chapter 5/README.md
  summarize_books_in_markdown/clean-code/Chapter 6/README.md
Labels: hacktoberfest-accepted, size/M

#429 clean-code Chapter 7,8 1차 수정
  summarize_books_in_markdown/clean-code/Chapter 7/README.md
  summarize_books_in_markdown/clean-code/Chapter 8/README.md
Labels: hacktoberfest-accepted, size/S

#430 Typo: Pragmatic chapter 2 오탈자 수정
  docs/etc/pragmatic-programmer/chapter-2.md
Labels: hacktoberfest-accepted, size/M

#431 테스트 주도 개발 오탈자 수정
  docs/test/test-driven-development/chapter-3.md
Labels: hacktoberfest-accepted, size/S

#432 Typo: 테스트 주도 개발 오탈자 수정
  docs/test/test-driven-development/chapter-4.md
  docs/test/test-driven-development/chapter-5.md
Labels: hacktoberfest-accepted, size/XS

#433 clean-code Chapter 9,10 오탈자 수정
  summarize_books_in_markdown/clean-code/Chapter 10/README.md
  summarize_books_in_markdown/clean-code/Chapter 9/README.md
Labels: hacktoberfest-accepted, size/S

#434 clean-code Chapter 11,12,13 오탈자 수정
  summarize_books_in_markdown/clean-code/Chapter 11/README.md
  summarize_books_in_markdown/clean-code/Chapter 12/README.md
  summarize_books_in_markdown/clean-code/Chapter 13/README.md
Labels: hacktoberfest-accepted, size/M

#435 clean-code Chapter 3 오탈자 수정
  summarize_books_in_markdown/clean-code/Chapter 3/README.md
Labels: hacktoberfest-accepted, size/S
